In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# YOUR CODE HERE (OPTION)

### Doc du lieu tu file

In [6]:
df = pd.read_csv('population_en_v2.csv')
df

,Provinces/city,Population density,Average population,Sex ratio,Population grow ratio,15+ labor,Region,Year
0,Ha Noi,2031.1,6761.3,97.80,1.93,3572.90,Hong river Delta,2011
1,Vinh Phuc,818.0,1011.4,97.60,0.38,608.30,Hong river Delta,2011
2,Bac Ninh,1292.6,1063.4,96.70,1.84,593.50,Hong river Delta,2011
3,Quang Ninh,191.4,1168.0,105.40,0.93,675.00,Hong river Delta,2011
4,Hai Duong,1044.6,1729.8,96.10,0.78,1071.00,Hong river Delta,2011
...,...,...,...,...,...,...,...,...
625,Can Tho,862.0,1240.7,98.65,0.39,716.78,Mekong Delta,2020
626,Hau Giang,450.0,729.8,101.38,-0.33,402.33,Mekong Delta,2020
627,Soc Trang,361.0,1195.7,99.34,-0.32,641.91,Mekong Delta,2020
628,Bac Lieu,342.0,913.5,100.15,0.58,507.76,Mekong Delta,2020
629,Ca Mau,229.0,1193.9,102.64,-0.03,669.77,Mekong Delta,2020

### Với mỗi cột có kiểu dữ liệu dạng số (numerical), các giá trị được phân bố như thế nào?

Ở dữ liệu này, hiện có 6 cột có vẻ là thuộc nhóm **numeric**: "Population density", "Average population", "Sex ratio", "Population grow ratio", "15+ labor", "Year". Tuy nhiên, ta chỉ xếp 5 cột gồm "Population density", "Average population", "Sex ratio", "Population grow ratio", "15+ labor" vào nhóm **numeric**. Vì cột "Year" thật ra thuộc nhóm **categorical** do đây là dữ liệu dùng để phân biệt dữ liệu của một tỉnh thành ở nhiều năm khác nhau.

In [24]:
numerical_cols = df[['Population density', 'Average population', 'Sex ratio', 'Population grow ratio','15+ labor']].copy()
numerical_cols

,Population density,Average population,Sex ratio,Population grow ratio,15+ labor
0,2031.1,6761.3,97.80,1.93,3572.90
1,818.0,1011.4,97.60,0.38,608.30
2,1292.6,1063.4,96.70,1.84,593.50
3,191.4,1168.0,105.40,0.93,675.00
4,1044.6,1729.8,96.10,0.78,1071.00
...,...,...,...,...,...
625,862.0,1240.7,98.65,0.39,716.78
626,450.0,729.8,101.38,-0.33,402.33
627,361.0,1195.7,99.34,-0.32,641.91
628,342.0,913.5,100.15,0.58,507.76
629,229.0,1193.9,102.64,-0.03,669.77

#### Số lượng/tỉ lệ các giá trị thiếu?
#### Min? max? → Có gì bất thường không?
Với mỗi cột numeric ta sẽ tính tỉ lệ % giá trị thiếu (từ 0 đến 100), min, max. Và lưu kết quả vào dataframe `nume_col_profiles_df`.
Dataframe này gồm có:
- 3 dòng là "missing_ratio", "min", "max" lần lượt là tỉ lệ các giá trị thiếu mỗi cột, min và max.
- 5 cột là "Population density", "Average population", "Sex ratio", "Population grow ratio", "15+ labor".

In [31]:
def missing_ratio(c):
    return  c.isna().sum()/len(df) * 100

def min(c):
    return c.min()

def max(c):
    return c.max()

nume_col_profiles_df = numerical_cols.agg([missing_ratio, min, max])
nume_col_profiles_df

,Population density,Average population,Sex ratio,Population grow ratio,15+ labor
missing_ratio,0.0,0.0,0.0,0.00,0.0
min,42.9,300.4,91.1,-1.22,199.6
max,4476.0,9227.6,114.1,5.30,4826.0